FROM ubuntu:14.04
LABEL name="learning"
LABEL email="fahadmeraj@gmail.com"
ENV name fahad
ENV pass password
RUN pwd>/tmp/1stpwd.txt
RUN cd /tmp
RUN pwd>/tmp/2ndpwd.txt
WORKDIR /tmp
RUN pwd>/tmp/3rdpwd.txt
